local Gift_UIRefs = require(script.Gift_UIRefs)
local Gifting_Controller = require(script.Gifting_Controller)
local Manager = require(script.Manager)
local PlayerGiftCard_Class = require(script.PlayerGiftCard_Class)
local PlayerGift_Class = require(script.PlayerGift_Class)
local RobuxBuyButton = require(script.RobuxBuyButton)
local ShopGUI_Refs = require(script.ShopGUI_Refs)

return {
	Manager = Manager,
	PlayerGift_Class = PlayerGift_Class,
	RobuxBuyButton = RobuxBuyButton,
	ShopGUI_Refs = ShopGUI_Refs,
	Gift_UIRefs = Gift_UIRefs,
	Gifting_Controller = Gifting_Controller,
	PlayerGiftCard_Class = PlayerGiftCard_Class,
}
